INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AF', 'Afghanistan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AL', 'Albania',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DZ', 'Algeria',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DS', 'American Samoa',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AD', 'Andorra',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AO', 'Angola',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AI', 'Anguilla',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AQ', 'Antarctica',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AG', 'Antigua and Barbuda',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AR', 'Argentina',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AM', 'Armenia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AW', 'Aruba',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AU', 'Australia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AT', 'Austria',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AZ', 'Azerbaijan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BS', 'Bahamas',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BH', 'Bahrain',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BD', 'Bangladesh',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BB', 'Barbados',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BY', 'Belarus',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BE', 'Belgium',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BZ', 'Belize',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BJ', 'Benin',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BM', 'Bermuda',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BT', 'Bhutan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BO', 'Bolivia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BA', 'Bosnia and Herzegovina',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BW', 'Botswana',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BV', 'Bouvet Island',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BR', 'Brazil',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IO', 'British Indian Ocean Territory',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BN', 'Brunei Darussalam',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BG', 'Bulgaria',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BF', 'Burkina Faso',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('BI', 'Burundi',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KH', 'Cambodia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CM', 'Cameroon',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CA', 'Canada',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CV', 'Cape Verde',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KY', 'Cayman Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CF', 'Central African Republic',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TD', 'Chad',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CL', 'Chile',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CN', 'China',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CX', 'Christmas Island',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CC', 'Cocos (Keeling) Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CO', 'Colombia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KM', 'Comoros',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CD', 'Democratic Republic of the Congo',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CG', 'Republic of Congo',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CK', 'Cook Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CR', 'Costa Rica',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('HR', 'Croatia (Hrvatska)',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CU', 'Cuba',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CY', 'Cyprus',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CZ', 'Czech Republic',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DK', 'Denmark',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DJ', 'Djibouti',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DM', 'Dominica',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DO', 'Dominican Republic',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TP', 'East Timor',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('EC', 'Ecuador',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('EG', 'Egypt',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SV', 'El Salvador',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GQ', 'Equatorial Guinea',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ER', 'Eritrea',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('EE', 'Estonia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ET', 'Ethiopia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FK', 'Falkland Islands (Malvinas)',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FO', 'Faroe Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FJ', 'Fiji',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FI', 'Finland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FR', 'France',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FX', 'France, Metropolitan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GF', 'French Guiana',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PF', 'French Polynesia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TF', 'French Southern Territories',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GA', 'Gabon',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GM', 'Gambia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GE', 'Georgia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('DE', 'Germany',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GH', 'Ghana',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GI', 'Gibraltar',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GK', 'Guernsey',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GR', 'Greece',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GL', 'Greenland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GD', 'Grenada',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GP', 'Guadeloupe',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GU', 'Guam',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GT', 'Guatemala',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GN', 'Guinea',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GW', 'Guinea-Bissau',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GY', 'Guyana',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('HT', 'Haiti',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('HM', 'Heard and Mc Donald Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('HN', 'Honduras',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('HK', 'Hong Kong',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('HU', 'Hungary',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IS', 'Iceland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IN', 'India',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IM', 'Isle of Man',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ID', 'Indonesia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IR', 'Iran (Islamic Republic of)',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IQ', 'Iraq',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IE', 'Ireland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IL', 'Israel',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('IT', 'Italy',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CI', 'Ivory Coast',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('JE', 'Jersey',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('JM', 'Jamaica',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('JP', 'Japan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('JO', 'Jordan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KZ', 'Kazakhstan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KE', 'Kenya',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KI', 'Kiribati',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KP', 'Korea, Democratic People''s Republic of',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KR', 'Korea, Republic of',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('XK', 'Kosovo',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KW', 'Kuwait',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KG', 'Kyrgyzstan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LA', 'Lao People''s Democratic Republic',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LV', 'Latvia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LB', 'Lebanon',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LS', 'Lesotho',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LR', 'Liberia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LY', 'Libyan Arab Jamahiriya',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LI', 'Liechtenstein',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LT', 'Lithuania',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LU', 'Luxembourg',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MO', 'Macau',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MK', 'North Macedonia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MG', 'Madagascar',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MW', 'Malawi',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MY', 'Malaysia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MV', 'Maldives',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ML', 'Mali',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MT', 'Malta',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MH', 'Marshall Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MQ', 'Martinique',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MR', 'Mauritania',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MU', 'Mauritius',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TY', 'Mayotte',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MX', 'Mexico',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('FM', 'Micronesia, Federated States of',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MD', 'Moldova, Republic of',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MC', 'Monaco',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MN', 'Mongolia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ME', 'Montenegro',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MS', 'Montserrat',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MA', 'Morocco',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MZ', 'Mozambique',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MM', 'Myanmar',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NA', 'Namibia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NR', 'Nauru',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NP', 'Nepal',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NL', 'Netherlands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AN', 'Netherlands Antilles',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NC', 'New Caledonia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NZ', 'New Zealand',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NI', 'Nicaragua',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NE', 'Niger',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NG', 'Nigeria',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NU', 'Niue',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NF', 'Norfolk Island',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('MP', 'Northern Mariana Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('NO', 'Norway',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('OM', 'Oman',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PK', 'Pakistan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PW', 'Palau',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PS', 'Palestine',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PA', 'Panama',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PG', 'Papua New Guinea',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PY', 'Paraguay',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PE', 'Peru',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PH', 'Philippines',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PN', 'Pitcairn',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PL', 'Poland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PT', 'Portugal',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PR', 'Puerto Rico',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('QA', 'Qatar',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('RE', 'Reunion',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('RO', 'Romania',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('RU', 'Russian Federation',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('RW', 'Rwanda',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('KN', 'Saint Kitts and Nevis',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LC', 'Saint Lucia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VC', 'Saint Vincent and the Grenadines',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('WS', 'Samoa',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SM', 'San Marino',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ST', 'Sao Tome and Principe',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SA', 'Saudi Arabia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SN', 'Senegal',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('RS', 'Serbia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SC', 'Seychelles',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SL', 'Sierra Leone',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SG', 'Singapore',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SK', 'Slovakia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SI', 'Slovenia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SB', 'Solomon Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SO', 'Somalia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ZA', 'South Africa',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GS', 'South Georgia South Sandwich Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SS', 'South Sudan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ES', 'Spain',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('LK', 'Sri Lanka',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SH', 'St. Helena',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('PM', 'St. Pierre and Miquelon',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SD', 'Sudan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SR', 'Suriname',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SJ', 'Svalbard and Jan Mayen Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SZ', 'Swaziland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SE', 'Sweden',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('CH', 'Switzerland',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('SY', 'Syrian Arab Republic',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TW', 'Taiwan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TJ', 'Tajikistan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TZ', 'Tanzania, United Republic of',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TH', 'Thailand',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TG', 'Togo',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TK', 'Tokelau',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TO', 'Tonga',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TT', 'Trinidad and Tobago',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TN', 'Tunisia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TR', 'Turkey',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TM', 'Turkmenistan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TC', 'Turks and Caicos Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('TV', 'Tuvalu',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('UG', 'Uganda',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('UA', 'Ukraine',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('AE', 'United Arab Emirates',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('GB', 'United Kingdom',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('US', 'United States',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('UM', 'United States minor outlying islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('UY', 'Uruguay',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('UZ', 'Uzbekistan',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VU', 'Vanuatu',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VA', 'Vatican City State',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VE', 'Venezuela',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VN', 'Vietnam',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VG', 'Virgin Islands (British)',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('VI', 'Virgin Islands (U.S.)',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('WF', 'Wallis and Futuna Islands',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('EH', 'Western Sahara',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('YE', 'Yemen',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ZM', 'Zambia',now(), now());
INSERT INTO countries (code, name, created_at, updated_at) VALUES ('ZW', 'Zimbabwe',now(), now());